server:
  port: 7060


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/test?serverTimezone=Asia/Seoul
    username: root
    password: 1111


thymeleaf:
  cache: false