server:
  port: 7060

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/blog?serverTimezone=Asia/Seoul
    username: root
    password: 1111
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      enabled: true


jwt:
  secret: 12345678901234567890123456789012